apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-workshop-content
spec:
  vendor: eduk8s.io
  title: Workshop Content
  description: Workshop on how to create Educates workshop content
  url: https://github.com/eduk8s/eduk8s-tutorials
  content:
    files: github.com/eduk8s/eduk8s-tutorials/workshops/lab-workshop-content
  session:
    namespaces:
      budget: medium
    resources:
      storage: 5Gi
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
    objects:
    - apiVersion: v1
      kind: Service
      metadata:
        name: $(session_namespace)-packager
        namespace: $(workshop_namespace)
      spec:
        type: ClusterIP
        ports:
        - name: 11111-tcp
          port: 11111
          targetPort: 11111
          protocol: TCP
        selector:
          deployment: $(session_namespace)
    - apiVersion: training.eduk8s.io/v1alpha2
      kind: Workshop
      metadata:
        name: $(session_namespace)-workshop
      spec:
        title: Sample Workshop
        description: My custom workshop
        content:
          files: http://$(session_namespace)-packager.$(workshop_namespace).svc.cluster.local:11111/
        session:
          namespaces:
            budget: small
          applications:
            terminal:
              enabled: true
              layout: split
            console:
              enabled: true
              vendor: octant
            editor:
              enabled: true
            examiner:
              enabled: true
    - apiVersion: training.eduk8s.io/v1alpha1
      kind: TrainingPortal
      metadata:
        name: $(session_namespace)-portal
      spec:
        portal:
          registration:
            type: anonymous
          sessions:
            maximum: 1
        workshops:
        - name: $(session_namespace)-workshop
          reserved: 0
          expires: 1h
          orphaned: 5m
