apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-et-self-guided-tour
spec:
  vendor: eduk8s.io
  title: Guided Tour of Educates
  description: A guided tour of Educates features and how it can be used
  url: https://github.com/eduk8s/eduk8s-tutorials
  content:
    files: github.com/eduk8s/eduk8s-tutorials/workshops/lab-et-self-guided-tour
  session:
    namespaces:
      budget: small
      security:
        policy: anyuid
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
      slides:
        enabled: true
      examiner:
        enabled: true
      docker:
        enabled: true
      registry:
        enabled: true
    dashboards:
    - name: Docs
      url: https://docs.edukates.io
    ingresses:
    - name: nginx-via-proxy
      protocol: http
      host: nginx.$(session_namespace).svc.cluster.local
