apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: eduk8s-tutorials
spec:
  portal:
    registration:
      enabled: false
    capacity: 1
  workshops:
  - name: lab-workshop-deployment
    expires: 24h
    orphaned: 5m
