apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: eduk8s-tutorials
spec:
  portal:
    password: educates
    registration:
      type: anonymous
    ingress:
      hostname: eduk8s-tutorials
    sessions:
      maximum: 1
    updates:
      workshop: true
    reserved: 0
  workshops:
  - name: lab-et-self-guided-tour
    expires: 30m
    orphaned: 5m
  - name: lab-et-workshop-playground
    expires: 120m
    orphaned: 30m
