apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: eduk8s-tutorials
spec:
  portal:
    password: educates
    registration:
      type: anonymous
    ingress:
      hostname: eduk8s-tutorials
    sessions:
      maximum: 1
    updates:
      workshop: true
    reserved: 0
  workshops:
  - name: lab-et-self-guided-tour
    expires: 30m
    orphaned: 10m
  - name: lab-et-basic-playground
    expires: 6h
    orphaned: 1h
  - name: lab-et-jdk8-playground
    expires: 6h
    orphaned: 1h
  - name: lab-et-jdk11-playground
    expires: 6h
    orphaned: 1h
  - name: lab-et-conda-playground
    expires: 6h
    orphaned: 1h
