apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: eduk8s-tutorials
spec:
  portal:
    registration:
      enabled: false
    sessions:
      maximum: 1
    updates:
      workshop: true
  workshops:
  - name: lab-workshop-content
    expires: 3h
    orphaned: 15m
  - name: lab-workshop-deployment
    expires: 3h
    orphaned: 15m
